This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./CLARREO_SMRD_mmd6.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file CLARREO_SMRD_mmd6.acn....done (222 entries accepted, 0 rejected).
Sorting entries.....done (2000 comparisons).
Generating output file CLARREO_SMRD_mmd6.acr....done (122 lines written, 0 warnings).
Output written in CLARREO_SMRD_mmd6.acr.
Transcript written in CLARREO_SMRD_mmd6.alg.
