This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./CLARREO_SMRD_mmd6_supplemental.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file CLARREO_SMRD_mmd6_supplemental.acn....done (431 entries accepted, 0 rejected).
Sorting entries......done (4097 comparisons).
Generating output file CLARREO_SMRD_mmd6_supplemental.acr....done (148 lines written, 0 warnings).
Output written in CLARREO_SMRD_mmd6_supplemental.acr.
Transcript written in CLARREO_SMRD_mmd6_supplemental.alg.
