This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./CLARREO_PCU_ICD.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file CLARREO_PCU_ICD.acn....done (261 entries accepted, 0 rejected).
Sorting entries.....done (2584 comparisons).
Generating output file CLARREO_PCU_ICD.acr....done (71 lines written, 0 warnings).
Output written in CLARREO_PCU_ICD.acr.
Transcript written in CLARREO_PCU_ICD.alg.
