This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./diff.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file diff.acn....done (276 entries accepted, 0 rejected).
Sorting entries.....done (2689 comparisons).
Generating output file diff.acr....done (72 lines written, 0 warnings).
Output written in diff.acr.
Transcript written in diff.alg.
